# fly.toml app configuration file generated for speach-app on 2024-05-29T12:11:45-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'speach-app'
primary_region = 'gru'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
